### ISSUE TITLE
Broken icon on GNOME software center

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.github.Flacon#9]
Hi. Currently, icon of this application appearing broken on GNOME software center - screenshot bellow:

![flacon-broken-icon](https://user-images.githubusercontent.com/25375330/83350976-a1b4ea00-a32f-11ea-8ba6-be4d788e5bb3.png)

**Comment by Eonfge** [comment]
The gift that keeps giving. Think it's related to #7

**Comment by Eonfge** [comment]
Give it a bit of time. Cache should be rebuilt. I hope that when the Flathub page is updated, the store also features the right version.

**Comment by Eonfge** [comment]
Version number and icon should be fixed now. You can manually run `flatpak update -y` to see the change.

**Comment by Nokia808** [comment]
@Eonfge 
Today, just few minutes ago, I saw the icon still broken in my GNOME software center on Fedora 32 X64 bit ! I, then perform "Refresh" for my GNOME software in section of update (refresh catch) but still icon is broken. Version of Flacon appearing in GNOME software is 6.0.0

My GNOME software version is 3.36.1

**Comment by Nokia808** [comment]
@Eonfge 
Sorry it is now appearing okay when I enter to it's section within GNOME software ! This happened after 3 close/open GNOME center after refresh the catch !! - see bellow:

![okay](https://user-images.githubusercontent.com/25375330/83384073-fdd24980-a3d5-11ea-8c8e-3644a715b40b.png)

But icon still appear broken if I look to it from other than Flacon section within GNOME software center ! - see bellow (look where I set my mouse pointer):

![broken](https://user-images.githubusercontent.com/25375330/83384150-2e19e800-a3d6-11ea-8206-4a6ab0db9c42.png)

What I have to do further ? It is from my side now !

**Comment by Nokia808** [comment]
Now issue completely resolved after restarting my OS. Flacon from FlatHub appearing any where within GNOME software center, appearing okay.

**Comment by Eonfge** [comment]
Thanks for keeping me updated. There is some caching going on with GNOME Software so it's not totally reliable if you want to see the latest changes.
